const RestaurentData = [
  {
    _id: 1,
    Image:
      "https://res.cloudinary.com/dmn7qksnf/image/upload/v1709398160/image1_bwtvj2.avif",
    name: "Biryani Zone",
    dishName:'Biryani',
    rating: 4.2,
    special: "Biryani, Chinese, North Indian...",
    old_price: "350",
    new_price:"300",
    time: "25 min",
  },
  {
    _id: 2,
    Image:
      "https://res.cloudinary.com/dmn7qksnf/image/upload/v1709398371/image2_baeb7z.avif",
    name: "Bhavana Foods",
    dishName:'Fast Food',
    rating: 3.0,
    special: "Biryani, Fast Food...",
    old_price: "350",
    new_price:"300",
    time: "25 min",
  },
  {
    _id: 3,
    Image:
      "https://res.cloudinary.com/dmn7qksnf/image/upload/v1709398448/image3_bkvumd.avif",
    rating: 3.0,
    name: "Biryani Means Heaven",
    dishName:'Biryani',
    special: "Biryani, Chinese, Street Food",
    old_price: "350",
    new_price:"300",
    time: "25 min",
  },
  {
    _id: 4,
    Image:
      "https://res.cloudinary.com/dmn7qksnf/image/upload/v1709398448/image4_uyfzbd.avif",
    rating: 3.0,
    name: "Sri Priyadharshini Hotel (pure veg)",
    dishName:'Dosa',
    special: "South Indian, Dosa",
    old_price: "100",
    new_price:"80",
    time: "25 min",
  },
  {
    _id: 0,
    Image:
      "https://res.cloudinary.com/dmn7qksnf/image/upload/v1709398449/image5_y7j3wj.avif",
    rating: 3.0,
    name: "Lucky9 Tadipatri Dum Biryani Ce...",
    dishName:'Biryani',
    special: "Biryani",
    old_price: "350",
    new_price:"300",
    time: "25 min",
  },
  {
    _id: 6,
    Image:
      "https://res.cloudinary.com/dmn7qksnf/image/upload/v1709398451/image6_fw5ucr.jpg",
    rating: 3.0,
    name: "The Vintage Cakes",
    dishName:'Cakes',
    special: "BBQ, Burger, Cafe, Desserts, ",
    old_price: "350",
    new_price:"300",
    time: "25 min",
  },
  {
    _id: 7,
    Image:
      "https://res.cloudinary.com/dmn7qksnf/image/upload/v1709398534/image7_vmrptr.avif",
    rating: 3.0,
    name: "Bombay Chat House",
    dishName:'Chat',
    special: "Ice Cream, Modern Indian, No",
    old_price: "350",
    new_price:"300",
    time: "25 min",
  },
  {
    _id: 8,
    Image:
      "https://res.cloudinary.com/dmn7qksnf/image/upload/v1709398534/image8_kgencj.avif",
    rating: 3.0,
    name: "Vivaha Bhojanambu",
    dishName:'Biryani',
    special: "Biryani, Andhra, Desserts, Beverages",
    old_price: "350",
    new_price:"300",
    time: "25 min",
  },
  {
    _id: 9,
    Image:
      "https://res.cloudinary.com/dmn7qksnf/image/upload/v1709398535/image9_hf69fb.avif",
    rating: 3.0,
    name: "Ravi teja Family Restaurant",
    dishName:'Biryani',
    special: "Biryani, North Indian, South Indian",
    old_price: "350",
    new_price:"300",
    time: "25 min",
  },
  {
    _id: 10,
    Image:
      "https://res.cloudinary.com/dmn7qksnf/image/upload/v1709398535/image10_twuae4.avif",
    rating: 3.0,
    name: "Vijaya Nagar Biryani House",
    dishName:'Seafood',
    special: "Biryani, Chinese, Roast Chicken, North Indian, Seafood",
    old_price: "350",
    new_price:"300",
    time: "30 min",
  },
  {
    _id: 11,
    Image:
      "https://res.cloudinary.com/dmn7qksnf/image/upload/v1709398535/image11_ksn9nf.avif",
    rating: 4.0,
    name: "S V Restaurant & Bar",
    dishName:'Chinese',
    special: "Chinese, Fast Food, Seafood, ",
    old_price: "400",
    new_price:"300",
    time: "30 min",
  },
  {
    _id: 12,
    Image:
      "https://res.cloudinary.com/dmn7qksnf/image/upload/v1709398535/image12_jmyp7v.avif",
    rating: 4.0,
    name: "Raghavendra Hotel",
    dishName:'Dosa',
    special: "South Indian, Dosa",
    old_price: "100",
    new_price:"70",
    time: "30 min",
  },
  {
    _id: 13,
    Image:
      "https://res.cloudinary.com/dmn7qksnf/image/upload/v1709398536/image13_h3xt9f.avif",
    rating: 4.0,
    name: "Jaggu Tadipatri Dum Biryani Sinc4.0/2005)",
    dishName:'Biryani with ',
    special: "Biryani",
    old_price: "400",
    new_price:"300",
    time: "30 min",
  },
  {
    _id: 14,
    Image:
      "https://res.cloudinary.com/dmn7qksnf/image/upload/v1709398537/image14_pxevqx.avif",
    rating: 4.0,
    name: "Lucky9 Tadipatri Dum Biryani Fa",
    dishName:'Biryani with charters',
    special: "Biryani, North Indian",
    old_price: "400",
    new_price:"300",
    time: "30 min",
  },
  {
    _id: 15,
    Image:
      "https://res.cloudinary.com/dmn7qksnf/image/upload/v1709398539/image15_v5ul75.avif",
    rating: 4.0,
    name: "Seena Oliga Center",
    dishName:'Oliga',
    special: "Andhra",
    old_price: "100",
    new_price:"70",
    time: "30 min",
  },
  {
    _id: 16,
    Image:
      "https://res.cloudinary.com/dmn7qksnf/image/upload/v1709398538/image16_usw6r8.avif",
    name: "Ammus Cake World",
    dishName:'Desserts',
    rating: 4.0,
    special: "Bakery",
    old_price: "400",
    new_price:"300",
    time: "40 min",
  },
  {
    _id: 17,
    Image:
      "https://res.cloudinary.com/dmn7qksnf/image/upload/v1709398538/image17_fee7bx.avif",
    name: "Idli N More",
    dishName:'Dosa',
    rating: 4.0,
    special: "Biryani, South Indian, Dosa",
    old_price: "100",
    new_price:"50",
    time: "40 min",
  },
  {
    _id: 18,
    Image:
      "https://res.cloudinary.com/dmn7qksnf/image/upload/v1709398538/image18_uwrhbp.avif",
    name: "SSV Home Food",
    dishName:'Roti',
    rating: 4.0,
    special: "South Indian, Chapathi",
    old_price: "400",
    new_price:"300",
    time: "40 min",
  },
  {
    _id: 19,
    Image:
      "https://res.cloudinary.com/dmn7qksnf/image/upload/v1709398538/image19_jdcskp.avif",
    rating: 4.0,
    name: "Ovenfresh Pizzas, Cakes and Des",
    dishName:'Desserts',
    special: "Bakery, Desserts, Ice Cream,",
    old_price: "400",
    new_price:"300",
    time: "40 min",
  },
  {
    _id: 20,
    Image:
      "https://res.cloudinary.com/dmn7qksnf/image/upload/v1709398539/image20_aysgsa.avif",
    name: "Just Bake",
    dishName:'Ice creams',
    rating: 4.0,
    special:
      "Bakery, Fast Food, Street Food, Momos, Ice Cream, Desserts, Beverages",
    old_price: "400",
    new_price:"300",
    time: "40 min",
  },
  {
    _id: 21,
    Image:
      "https://res.cloudinary.com/dmn7qksnf/image/upload/v1709398539/image21_arezsp.avif",
    name: "Bite N Sip",
    dishName:'Fast Food',
    rating: 4.2,
    special: "Continental, Biryani, Fast Food",
    old_price: "450",
    new_price:"300",
    time: "40 min",
  },
  {
    _id: 22,
    Image:
      "https://res.cloudinary.com/dmn7qksnf/image/upload/v1709398539/image22_m5r267.avif",
    name: "The Prison",
    dishName:'Biryani',
    rating: 4.2,
    special: "North Indian, Biryani, Chines",
    old_price: "450",
    new_price:"300",
    time: "10 min",
  },
  {
    _id: 23,
    Image:
      "https://res.cloudinary.com/dmn7qksnf/image/upload/v1709398540/image23_g7dkq5.avif",
    name: "TFM Sky Lounge",
    dishName:'Chicken Pizaa',
    rating: 4.2,
    special: "Pizza, Burger, Italian, Continental",
    old_price: "450",
    new_price:"300",
    time: "30 min",
  },
  {
    _id: 24,
    Image:
      "https://res.cloudinary.com/dmn7qksnf/image/upload/v1709398540/image24_w9ncl0.avif",
    name: "Indian Bowl Co",
    dishName:'Rice & Chicken Curry',
    rating: 4.2,
    special: "Hyderabadi",
    old_price: "450",
    new_price:"300",
    time: "15 min",
  },
  {
    _id: 25,
    Image:
      "https://res.cloudinary.com/dmn7qksnf/image/upload/v1709398540/image25_yxaxji.avif",
    name: "Royal Rolls",
    dishName:'Chicken Roll',
    rating: 4.2,
    special: "Rolls",
    old_price: "450",
    new_price:"300",
    time: "30 min",
  },
  {
    _id: 26,
    Image:
      "https://res.cloudinary.com/dmn7qksnf/image/upload/v1709398541/image26_cgq0c0.avif",
    name: "Indiana Burgers",
    dishName:'Burgers',
    rating: 4.2,
    special: "Burger, Fast Food, Rolls, Beverages, Desserts, Shake",
    old_price: "450",
    new_price:"300",
    time: "20 min",
  },
  {
    _id: 27,
    Image:
      "https://res.cloudinary.com/dmn7qksnf/image/upload/v1709398541/image27_mn8ojn.avif",
    rating: 4.2,
    name: "Kaati Zone Rolls and Wraps",
    dishName:'Kaati Zone Roll',
    special: "Rolls, Wraps, Fast Food, Des",
    old_price: "450",
    new_price:"300",
    time: "30 min",
  },
  {
    _id: 28,
    Image:
      "https://res.cloudinary.com/dmn7qksnf/image/upload/v1709398542/image28_youtbz.avif",
    name: "Shawarma Spot",
    dishName:'French Fries',
    rating: 4.2,
    special: "Shawarma, Fast Food, Shake, Beverages",
    old_price: "450",
    new_price:"300",
    time: "30 min",
  },
  {
    _id: 29,
    Image:
      "https://res.cloudinary.com/dmn7qksnf/image/upload/v1709398542/image29_po6jft.avif",
    rating: 4.2,
    name: "Lingamiya Tadipatri Dum Biryan",
    dishName:'Biryani',
    special: "Biryani",
    old_price: "450",
    new_price:"300",
    time: "25 min",
  },
  {
    _id: 30,
    Image:
      "https://res.cloudinary.com/dmn7qksnf/image/upload/v1709398960/image30_jnxhvp.avif",
    rating: 4.2,
    name: "Ramaiah Idli Center",
    dishName:'Idli',
    special: "Andhra, South Indian, Idli",
    old_price: "450",
    new_price:"300",
    time: "30 min",
  },
];

export default RestaurentData;
